### ISSUE TITLE
데이터베이스 접근 로직 테스트 정의

### ISSUE THREAD

**Issue by yunhoknight** [yunhoknight/fastcampus-project-admin#3]
## Description

어드민 프로젝트에 데이터베이스를 사용할 수 있게끔 환경을 구성하고 테스트를 정의함
## Todo
1. [x] DB 만들기
2. [x] 계정 권한 추가
3. [x] IDE 접근 환경 꾸미기
4. [x] Repository 코드 작성
5. [x] 관련 테스트 작성
