### ISSUE TITLE
뷰 엔드포인트 테스트 보완

### ISSUE THREAD

**Issue by yunhoknight** [yunhoknight/fastcampus-project-admin#31]
## Description

이전 뷰엔드포인트 테스트 작성시 테스트가 통과하지 못한 내용을
테스트만 통과될 수 있도록 수정보완
## Todo
1. [ ] 메인 페이지
2. [ ] 게시글 관리 페이지
3. [ ] 게시글 댓글 관리 페이지
4. [ ] 유저 관리 페이지
5. [ ] 어드민 유저 페이지
